### ISSUE TITLE
(Plans and remaing todos for) Release 1.6.0

### ISSUE THREAD

**Issue by hartwork** [tenox7/ttyplot#134]
Hi @edgar-bonet  and @tenox7 ,

@edgar-bonet and I got a good deal of things done already for 1.6.0 on `development`, I have added a [milestone "1.6.0"](https://github.com/tenox7/ttyplot/milestone/1) in the meantime and tagged all related pull requests with it, for the list of all 1.6.0 merged ones see https://github.com/tenox7/ttyplot/pulls?q=is%3Apr+is%3Amerged+milestone%3A1.6.0 for a quick impression/overview.

I'm creating this issue for us to collect things that are either (a) necessary (as in blocking release 1.6.0) or (b) planned for 1.6.0 but optional in nature — just so we don't miss something and everyone is on the same page. These are all things intended for *before* we hand over to @tenox7 for acceptance testing, at least that was the idea. The two of you, please consider this text a wiki and edit/extend the task list below as needed, the checkbox are just fancy `- [ ] text` and `- [x] text` syntax, very low-tech you'll see…

## Necessary

- [x] Finish and merge open pull requests at https://github.com/tenox7/ttyplot/pulls
- [x] Check if toggle `r` is working as expected
- [x] Document hotkeys `q` and `r` in man page — #141 
- [x] (Document hotkeys `q` and `r` in help output?) — #141 
- [x] Check case `ttyplot <<<NaN`
- [x] Do more debugging with `/dev/random` input, rendering looks somewhat unexpected, needs a closer look
- [ ] Check back with @tenox7 if he's good with axes already being drawn when still in "waiting for data from stdin" mode, which is status quo on branch `development`

## Planned but Optional

- [x] Check if making functions (and global variables) static makes any difference to the produced assembly, may allow more inlining — #136
- [x] Update the clock on the full system's seconds
  - #144
  - #145
  - #146
- [x] Find a non-racy alternative to `pselect_without_signal_starvation()`
  - #142 
  - #143 

Looking forward to your edits! :beers:

**Comment by edgar-bonet** [comment]
Thanks @hartwork! I was myself getting a bit lost with all these completed and planned changes. I do appreciate this summary.

Also, I added a couple of “optional” items to the list. Ideas I have been considering.

**Comment by hartwork** [comment]
@edgar-bonet the rate mode and rate toggle hotkey turned out working properly in my testing. Could you take over documenting hotkeys `q` and `r`? After that and merging the [open pull requests](https://github.com/tenox7/ttyplot/pulls) I think we'd be ready to give this to users, and then we can still have a release 1.6.0 this year.

**Comment by hartwork** [comment]
@edgar-bonet I can probably demo an idea for "Update the clock on the full system's seconds" unless you're already working on it or would rather play with it yourself. Happy either way.

**Comment by edgar-bonet** [comment]
@hartwork: I wanted to play with it but, since I don't have time to do all I want to do, I would say: go ahead please.

**Comment by hartwork** [comment]
Now bumped to 1.6.0 in Gentoo: https://github.com/gentoo/gentoo/commit/73f5c0151f6519f36046a7228937ae938e42559e
